version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: secret-santa-db
    environment:
      POSTGRES_DB: secretsanta
      POSTGRES_USER: secret_user
      POSTGRES_PASSWORD: secret
    ports:
      - "5435:5432"
    volumes:
      - ./src/main/resources/schema.sql:/docker-entrypoint-initdb.d/schema.sql
