spring.application.name=secret-gifter-backend

spring.datasource.url=jdbc:postgresql://localhost:5435/secretsanta
spring.datasource.username=secret_user
spring.datasource.password=secret

spring.datasource.driver-class-name=org.postgresql.Driver

